/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    pages: Page;
    media: Media;
    users: User;
    redirects: Redirect;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    settings: Settings;
    header: Header;
    footer: Footer;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug?: string | null;
  pageType?: ('default' | 'restaurant' | 'transparentHeader') | null;
  blocks?:
    | (
        | {
            flexSizes?:
              | {
                  size: 'default' | 'sm' | 'md' | 'lg' | 'xl';
                  layout?: {
                    flexDirection?: ('row' | 'row-reverse' | 'col' | 'col-reverse') | null;
                    flexWrap?: ('nowrap' | 'wrap' | 'wrap-reverse') | null;
                    justifyContent?:
                      | (
                          | 'justify-start'
                          | 'justify-end'
                          | 'justify-center'
                          | 'justify-between'
                          | 'justify-around'
                          | 'justify-evenly'
                        )
                      | null;
                    alignItems?:
                      | ('items-stretch' | 'items-start' | 'items-end' | 'items-center' | 'items-baseline')
                      | null;
                    gap?: number | null;
                    childWidth?: number | null;
                  };
                  id?: string | null;
                }[]
              | null;
            blocks?:
              | (
                  | {
                      richText: {
                        root: {
                          children: {
                            type: string;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          type: string;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      cta?: string | null;
                      url?: string | null;
                      richText_html?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'rich_text';
                    }
                  | {
                      cta: string;
                      url: string;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'cta_button';
                    }
                  | {
                      items?:
                        | {
                            header: string;
                            body: string;
                            cta?: string | null;
                            url?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'accordion';
                    }
                  | {
                      header: string;
                      body: string;
                      cta?: string | null;
                      url?: string | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'full_width_card';
                    }
                  | {
                      items?:
                        | {
                            image?: string | Media | null;
                            header: string;
                            body: string;
                            cta?: string | null;
                            url?: string | null;
                            secondary_cta?: string | null;
                            secondary_url?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'shuffle';
                    }
                  | {
                      text: string;
                      quotee?: string | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'quote';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'flex_layout';
          }
        | {
            blocks?:
              | (
                  | {
                      richText: {
                        root: {
                          children: {
                            type: string;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          type: string;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      cta?: string | null;
                      url?: string | null;
                      richText_html?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'rich_text';
                    }
                  | {
                      cta: string;
                      url: string;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'cta_button';
                    }
                  | {
                      items?:
                        | {
                            header: string;
                            body: string;
                            cta?: string | null;
                            url?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'accordion';
                    }
                  | {
                      header: string;
                      body: string;
                      cta?: string | null;
                      url?: string | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'full_width_card';
                    }
                  | {
                      items?:
                        | {
                            image?: string | Media | null;
                            header: string;
                            body: string;
                            cta?: string | null;
                            url?: string | null;
                            secondary_cta?: string | null;
                            secondary_url?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'shuffle';
                    }
                  | {
                      text: string;
                      quotee?: string | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'quote';
                    }
                )[]
              | null;
            margins?:
              | {
                  type?: ('mobile' | 'tablet' | 'desktop') | null;
                  top?: number | null;
                  right?: number | null;
                  bottom?: number | null;
                  left?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'container_layout';
          }
        | {
            type?: ('title' | 'cta' | 'content') | null;
            backgroundImage?: string | Media | null;
            contentAlignment?: ('justify-start' | 'justify-center' | 'justify-end') | null;
            blocks?:
              | (
                  | {
                      richText: {
                        root: {
                          children: {
                            type: string;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          type: string;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      cta?: string | null;
                      url?: string | null;
                      richText_html?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'rich_text';
                    }
                  | {
                      cta: string;
                      url: string;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'cta_button';
                    }
                  | {
                      items?:
                        | {
                            header: string;
                            body: string;
                            cta?: string | null;
                            url?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'accordion';
                    }
                  | {
                      header: string;
                      body: string;
                      cta?: string | null;
                      url?: string | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'full_width_card';
                    }
                  | {
                      items?:
                        | {
                            image?: string | Media | null;
                            header: string;
                            body: string;
                            cta?: string | null;
                            url?: string | null;
                            secondary_cta?: string | null;
                            secondary_url?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'shuffle';
                    }
                  | {
                      text: string;
                      quotee?: string | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'quote';
                    }
                )[]
              | null;
            title?: string | null;
            subtext?: string | null;
            cta?: string | null;
            url?: string | null;
            margins?:
              | {
                  type?: ('mobile' | 'tablet' | 'desktop') | null;
                  top?: number | null;
                  right?: number | null;
                  bottom?: number | null;
                  left?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero_header';
          }
        | {
            type?: ('light' | 'dark') | null;
            cards?:
              | {
                  header: string;
                  body: string;
                  cta?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            margins?:
              | {
                  type?: ('mobile' | 'tablet' | 'desktop') | null;
                  top?: number | null;
                  right?: number | null;
                  bottom?: number | null;
                  left?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'card_list';
          }
        | {
            backgroundImage?: string | Media | null;
            alignment?: ('justify-start' | 'justify-center' | 'justify-right') | null;
            blocks?:
              | (
                  | {
                      richText: {
                        root: {
                          children: {
                            type: string;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          type: string;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      cta?: string | null;
                      url?: string | null;
                      richText_html?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'rich_text';
                    }
                  | {
                      cta: string;
                      url: string;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'cta_button';
                    }
                  | {
                      items?:
                        | {
                            header: string;
                            body: string;
                            cta?: string | null;
                            url?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'accordion';
                    }
                  | {
                      header: string;
                      body: string;
                      cta?: string | null;
                      url?: string | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'full_width_card';
                    }
                  | {
                      items?:
                        | {
                            image?: string | Media | null;
                            header: string;
                            body: string;
                            cta?: string | null;
                            url?: string | null;
                            secondary_cta?: string | null;
                            secondary_url?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'shuffle';
                    }
                  | {
                      text: string;
                      quotee?: string | null;
                      margins?:
                        | {
                            type?: ('mobile' | 'tablet' | 'desktop') | null;
                            top?: number | null;
                            right?: number | null;
                            bottom?: number | null;
                            left?: number | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'quote';
                    }
                )[]
              | null;
            margins?:
              | {
                  type?: ('mobile' | 'tablet' | 'desktop') | null;
                  top?: number | null;
                  right?: number | null;
                  bottom?: number | null;
                  left?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content_banner';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | Media | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('admin' | 'user')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Settings {
  id: string;
  postsPage?: (string | null) | Page;
  projectsPage?: (string | null) | Page;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}